# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/myCPUfor2018/myCPUfor2018.srcs/sources_1/ip/DM/DM.xci
# IP: The module: 'DM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/myCPUfor2018/myCPUfor2018.srcs/sources_1/ip/DM/DM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/myCPUfor2018/myCPUfor2018.srcs/sources_1/ip/DM/DM.xci
# IP: The module: 'DM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/myCPUfor2018/myCPUfor2018.srcs/sources_1/ip/DM/DM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
