webtalk_init -webtalk_dir D:/myCPUfor2018/myCPUfor2018.sim/sim_1/behav/xsim/xsim.dir/testbench_cpu_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Aug  2 22:24:10 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "205589051_15690819_210558907_866" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "921f6266-28de-4d2c-a553-c0db861759d2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5d997b0142a240f1ab228876f938affe" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "88" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.98_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13824_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1243091872 -regid "205589051_15690819_210558907_866" -xml D:/myCPUfor2018/myCPUfor2018.sim/sim_1/behav/xsim/xsim.dir/testbench_cpu_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/myCPUfor2018/myCPUfor2018.sim/sim_1/behav/xsim/xsim.dir/testbench_cpu_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/myCPUfor2018/myCPUfor2018.sim/sim_1/behav/xsim/xsim.dir/testbench_cpu_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
